### ISSUE TITLE
Store not up-to-date in a new tab on a specific route

### ISSUE THREAD

**Issue by VinceBT** [danielr18/connected-next-router#9] opened 2019-02-05 13:01 UTC
If I go from `/` to `/example` I can see the event triggered on the redux console and the store is changed, but if I open a new tab with `/example` directly, the store shows `/`as pathname

**Comment by danielr18** [comment] 2019-02-05 13:07
Are you using the `initialRouterState` helper?

https://github.com/danielr18/connected-next-router/blob/e2052ebe7e292fa5c951c7092584748dc3e8a9bd/examples/basic/store/configure-store.js#L20

**Comment by danielr18** [comment] 2019-02-05 13:33
Would you mind sharing a minimal reproduction so that I can help further?

It seems to work fine in the example in the repo:
![image](https://user-images.githubusercontent.com/9046616/52276631-7683db80-2931-11e9-962c-8b2728922253.png)

**Comment by VinceBT** [comment] 2019-02-05 13:41
Redux devtools and address bar
![image](https://user-images.githubusercontent.com/1362505/52276895-ab088f00-2953-11e9-8d39-b9d37571269b.png)
Complete redux setup file
```js
import { createRouterMiddleware, initialRouterState, routerReducer } from 'connected-next-router'
import { applyMiddleware, combineReducers, createStore } from 'redux'
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly'
import { i18nState } from 'redux-i18n'
import createSagaMiddleware from 'redux-saga'
import Immutable from 'seamless-immutable'

import entities from './entities'
import rootSaga from './sagas'


const reducers = {
  i18nState,
  router: routerReducer,
}

Object.keys(entities)
  .forEach((key) => {
    reducers[key] = entities[key].reducer
  })

const routerMiddleware = createRouterMiddleware()
const sagaMiddleware = createSagaMiddleware()
const enhancer = composeWithDevTools(applyMiddleware(routerMiddleware, sagaMiddleware))
const combinedReducers = combineReducers(reducers)


export default (initialState = {}, options) => {
  if (options.isServer) {
    // eslint-disable-next-line
    initialState.router = initialRouterState(options.asPath)
  }

  const store = createStore(combinedReducers, Immutable(initialState), enhancer)

  sagaMiddleware.run(rootSaga)
  return store
}

export { sagaMiddleware as saga }
```
Usage of `ConnectedRouter`
![image](https://user-images.githubusercontent.com/1362505/52276984-e1460e80-2953-11e9-9515-de15b947e824.png)

**Comment by VinceBT** [comment] 2019-02-05 13:47
I get this when logging as following:
`console.log('isServer', options.isServer, ', path:', options.asPath, ', routerState: ', initialState.router)`
![image](https://user-images.githubusercontent.com/1362505/52277410-f5d6d680-2954-11e9-8288-2ed4f3f26809.png)

**Comment by danielr18** [comment] 2019-02-05 13:58
Alright, I'm able to recreate this by installing `next-redux-wrapper: 3.0.0-alpha.0`.

I'm working now on a fix.

FYI: A minimal reproduction is code that I can run on my side to get the same output, e.g. a simple example showing the issue with https://codesandbox.io/

**Comment by VinceBT** [comment] 2019-02-05 14:04
Thank you @danielr18
Sorry for not making a reproduction, I am not very used to it.

**Comment by VinceBT** [comment] 2019-02-05 14:10
Here is my temporary workaround
![image](https://user-images.githubusercontent.com/1362505/52278769-1c4a4100-2958-11e9-851c-88d0e6d1a353.png)

**Comment by danielr18** [comment] 2019-02-05 15:03
I recommend creating a shallow copy of the initial state meanwhile:

```
export const configureStore = (initialState = {}, { isServer, asPath }) => {
  const routerMiddleware = createRouterMiddleware()
  const state = { ...initialState }
  if (isServer) {
    state.router = initialRouterState(asPath)
  }

  const store = createStore(rootReducer, state, bindMiddleware([routerMiddleware]))
  return store
}
```

It was bit hard to debug, but the issue is that after v2.0.0, they recreate the store in the server and client (see https://github.com/zeit/next.js/pull/4295#pullrequestreview-118516366) but if you mutate the initialState in the server, which happens when store is recreated but this time outside `getInitialProps`, so there's no `asPath`, then when Next.js serializes the initial props, it would serialize the mutated initialState, which now differs from what you returned in `getInitialProps`, making it a bit confusing.

**Comment by danielr18** [comment] 2019-02-05 15:14
Actually, I think it's better to not rely on `isServer`. We really only want to set the initial state if we are in `getInitialProps`, and `asPath` is only defined when `configureStore` is called from `getInitialProps`, so this code is better.

```javascript
export const configureStore = (initialState = {}, { asPath }) => {
  const routerMiddleware = createRouterMiddleware()

  if (asPath) {
    initialState.router = initialRouterState(asPath)
  }

  const store = createStore(rootReducer, initialState, bindMiddleware([routerMiddleware]))
  return store
}
```

**Comment by VinceBT** [comment] 2019-02-05 15:17
Your workaround from https://github.com/danielr18/connected-next-router/issues/9#issuecomment-460670282 made that there was a state flicker during the render but the one from https://github.com/danielr18/connected-next-router/issues/9#issuecomment-460674472 seems to fix the problem for now

**Comment by danielr18** [comment] 2019-02-05 15:20
Yes, first example was wrong as it leads to server and client rendering with different redux states, I've deleted it to avoid confusing other people.

I'm going to replace the code in the example, and close this issue.

**Closed** 2019-02-05 15:22 UTC
