### ISSUE TITLE
push method reloads page

### ISSUE THREAD

**Issue by pavel06081991** [danielr18/connected-next-router#21] opened 2019-06-26 14:03 UTC
I'm using push method to change url query params. There are two issues I see:
1. I want to update only query params, so I only pass query without pathname. But application crashes.
2. When I pass query and pathname(the current page url) it works, but page is fully reloaded from the server with new url params. How to avoid page reloading? I just changed query params, why is it reloading?

**Comment by danielr18** [comment] 2019-06-26 15:38
Hello,

1 - Not sure if this is supported by Next.js Router, I think it's required to pass an URL, and if you are using an URL object, that would mean the pathname.

2 - I can't recreate this in the basic example, is it possible for you to create a minimal reproduction I can check?

**Comment by pavel06081991** [comment] 2019-07-01 12:51
@danielr18 sorry now I've read more about next js router and how it works. The described issues are not issues. But I found another issue.  When I use push method with shallow: true param like this:
```javascript
    push({ pathname, query }, { pathname, query }, { shallow: true })
```

then url in browser is updated with new query params but in redux state related to router there are no changes.

**Comment by danielr18** [comment] 2019-07-10 14:58
Can you create a minimal reproduction in codesandbox or a repository?

And yes, it's a mistake that 0.0.7 is marked as latest, it's because that's the last version that was published, v0 is for Redux v5 and v1 is for Redux v6 and v7.

**Comment by danielr18** [comment] 2019-10-31 00:25
Closed due to inactivity

**Closed by danielr18** 2019-10-31 00:25 UTC

**Comment by Guneetgstar** [comment] 2020-10-30 22:49
Yes redux state doesn't change calling push action from the props

**Comment by Guneetgstar** [comment] 2020-10-30 23:08
But it didn't work in case of an error page only -_-
